In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
b = np.array([[3, 2, 1], [3, 2, 1], [3, 2, 1]])
print(a)
print(b)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[3 2 1]
 [3 2 1]
 [3 2 1]]


In [4]:
aL = a.tolist()
bL = b.tolist()

def matrix_multiply(A, B):
    # A 的列数必须等于 B 的行数
    if len(A[0]) != len(B):
        raise ValueError("A 的列数必须等于 B 的行数")

    # 初始化结果矩阵
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

    # 进行矩阵乘法
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]

    return result

print(matrix_multiply(aL, bL))

[[18, 12, 6], [18, 12, 6], [18, 12, 6]]


In [5]:
#TODO:计算a,b的矩阵乘结果，并输出
ab = a.dot(b)
print(ab)
ab = a @ b
print(ab)

[[18 12  6]
 [18 12  6]
 [18 12  6]]
[[18 12  6]
 [18 12  6]
 [18 12  6]]


In [6]:
#TODO：将结果转换回Python List形式，并输出
ab_list = ab.tolist()
print(ab_list)

[[18, 12, 6], [18, 12, 6], [18, 12, 6]]


1. 写一个函数实现乘法
2. 减法， 除法，元素乘法，幂运算，矩阵的逆，矩阵转置，矩阵行列式，矩阵特征值和特征向量